version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: basketMongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: basketRedis


volumes:
  mongodb: